name: zpp-app
services:
  frontend:
    build: ./frontend
    ports:
      - 80:80

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - images_volume:/image
    ports:
      - 9090:9090
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db

  db:
    image: postgis/postgis:17-3.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env 
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  images_volume: