name: app
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 9090:9090
    depends_on:
      - db
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=zpp
      - POSTGRES_USER=zpp
      - POSTGRES_DB=zpp

volumes:
  postgres_data: