name: app
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 9090:9090
    depends_on:
      - db
    env_file:
      - .dev.env 
    environment:
      - POSTGRES_HOST=db
  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .dev.env 

volumes:
  postgres_data: